### ISSUE TITLE
1b. Documento del alcance - Se incluye la EDT (Estructura de División del Trabajo) en formato tabular (10 puntos)

### ISSUE THREAD

**Issue by lfnavarroj1** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#11]

**Comment by sriveros21** [comment]
Se incluye en el documento de entrega: https://uniandes.sharepoint.com/:w:/r/sites/Proyectointegrador1/_layouts/15/doc2.aspx?sourcedoc=%7B27419b39-7398-44b0-8a47-e6f0f3036264%7D&action=edit&wdPid=19a465c9
