### ISSUE TITLE
2a. Hoja de trabajo con objetivos - Se definen al menos 2 objetivos.

### ISSUE THREAD

**Issue by lfnavarroj1** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#14]

**Comment by sriveros21** [comment]
Se definen objetivos en archivo de entrega: 

Objetivos 

1. Posicionamiento: Posicionarse como líder en aplicaciones de salud y bienestar deportivo enfocadas en deportistas no profesionales en Latinoamérica. 
2. Diferenciación: Ofrecer un servicio que se distingue por considerar las características físicas, culturales y de alimentación específicas de la población latinoamericana. 
3. Herramientas de Salud y Bienestar: Facilitar a los deportistas no profesionales acceso a herramientas y guías para mejorar sus hábitos de deporte y alimentación. 
4. Apoyo Logístico: Ofrecer soporte logístico a organizadores de eventos deportivos masivos y participantes. 
5. Servicios Complementarios: Integrar la aplicación con empresas que brindan servicios adicionales para enriquecer la experiencia de los deportistas no profesionales.
