### ISSUE TITLE
2b. Restricciones - Se definen al menos 2 restricciones de negocio

### ISSUE THREAD

**Issue by lfnavarroj1** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#16]

**Comment by sriveros21** [comment]
Restricciones de negocio definidas: 
Restricciones de negocio. 

1. Tiempo de Desarrollo: El proyecto debe completarse en 16 semanas, dividido en dos fases de 8 semanas cada una para diseño y desarrollo. 
2. Recursos Humanos: El equipo de desarrollo está limitado a 4 personas para arquitectura y desarrollo. 
3. Integración de Socios de Negocio: La plataforma debe permitir agregar socios de negocio de manera sencilla y flexible sin requerir cambios en las aplicaciones web o móvil. 
4. Disponibilidad Geográfica: Garantizar la disponibilidad del sistema en toda Latinoamérica. 
5. Plataforma Multidispositivo: Implementar tanto la aplicación web como móvil. 
6. Expansión de Deportes: Permitir la inclusión de nuevos deportes sin superar las 20 horas/hombre de desarrollo.
