### ISSUE TITLE
HU001 - Registrar usuario

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#48]
Como usuario potencial de “SportApp” en la versión web quiero registrarme proporcionando mis datos basicos (nombre, email, contrasena) para crear mi perfil y gestionar mis entrenamientos, prácticas deportivas y planes de alimentación.

[Detalle HU001](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU001)

La implementacion de esta historia incluye el cumplimiento de las [HA001](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/129): Disponibilidad en el registro de usuarios.
Y [HA002](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/130): Latencia al momento de registrar un usuario.

**Comment by sriveros21** [comment]
Finish in: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/17
