### ISSUE TITLE
HU003 - Iniciar sesión

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#50]
Como usuario registrado de “SportApp” quiero iniciar sesión en la versión web para acceder a mis datos y funciones personalizadas.

[Detalle HU003](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU003)

La finalizacion de esta historia de usuario incluye el cumplimiento de las [HA004:](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/132) Seguridad en transferencia de datos al enviar información al sistema. y [HA005](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/133): Confidencialidad en registro de usuarios

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/37
