### ISSUE TITLE
HU004 - Cerrar sesión

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#51]
Como usuario logueado de “SportApp” quiero cerrar sesión en la versión web para asegurar que mi información permanezca privada.

[Detalle HU004](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU004)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/37
