### ISSUE TITLE
HU005 - Registrar datos demográficos y fisiológicos.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#52]
Como deportista no profesional registrado en “SportApp” quiero registrar mis datos demográficos y fisiológicos en la versión web para personalizar mis entrenamientos.

[Detalle HU005](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU005)

**Comment by CristinaGM4** [comment]
Como deportista no profesional registrado en “SportApp” quiero registrar mis datos  demográficos y fisiológicos en la versión web para personalizar mis entrenamientos.

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/19
