### ISSUE TITLE
HU006 - Registrar datos de hábitos deportivos.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#53]
Como deportista no profesional registrado en “SportApp” quiero registrar datos de mis hábitos deportivos en la versión web para que mis entrenamientos se ajusten a mi rutina.

[Detalle HU006](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU006)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/19
