### ISSUE TITLE
HU009 - Registrar datos de hábitos alimenticios.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#56]
Como deportista no profesional registrado en “SportApp” quiero registrar datos de mis hábitos alimenticios en la versión Web para recibir recomendaciones personalizadas de nutrición y entrenamientos.

[Detalle HU009](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU009)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/31
