### ISSUE TITLE
HU010 - Crear plan de entrenamiento según el perfil.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#57]
Como profesional de servicios complementarios registrada en “SportApp” quiero crear planes de entrenamiento personalizados para deportistas para asignarlos a los deportistas que usan mis servicios.

[Detalle HU010](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU010)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/24
