### ISSUE TITLE
HU011 - Ver historial de entrenamiento

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#58]
Como usuario registrado en SportApp, quiero ver el historial de entrenamientos, para llevar un control del progreso.

[Detalle HU011](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU011)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/25
