### ISSUE TITLE
HU014 - Crear plan de alimentación según el perfil.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#61]
Como profesional de servicios complementarios registrado en SportApp, quiero crear un plan de alimentación personalizado según el perfil deportivo y necesidades nutricionales del usuario, para optimizar su rendimiento y recuperación. 

[Detalle HU014](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU014)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/24
