### ISSUE TITLE
HU016 - Seleccionar plan de afiliación.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#63]
Como deportista no profesional registrado en SportApp, quiero seleccionar un plan de afiliación para
adaptar los servicios ofrecidos a mis necesidades deportivas y preferencias.

[Detalle HU016](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU016)

**Comment by sriveros21** [comment]
Finished in: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/18
