### ISSUE TITLE
HU017 - Asociar servicios médicos deportivos.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#64]
Como deportista no profesional registrado en SportApp, quiero asociar servicios médicos deportivos a mi perfil para tener acceso rápido y eficiente en caso de necesidad.

[Detalle HU017](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU017)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/35
