### ISSUE TITLE
HU018 - Integrar servicios y eventos en el calendario.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#65]
Como usuario registrado en SportApp, quiero integrar un calendario de eventos y servicios y eventos para facilitar la planificación y logística de mis servicios ofrecidos.

[Detalle HU018](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU018)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/30
