### ISSUE TITLE
HU019 - Publicar servicios.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#66]
Como profesional de servicios complementarios registrado en SportApp, quiero publicar mis servicios en SportApp para incrementar mi visibilidad y alcance a más usuarios.

[Detalle HU019](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU019)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/12
