### ISSUE TITLE
HU020 - Visualizar disponibilidad de servicios.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#67]
Como deportista no profesional registrado en SportApp, quiero visualizar la disponibilidad de los servicios ofrecidos para planificar eficientemente mis actividades deportivas.

[Detalle HU020](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU020)

**Comment by sriveros21** [comment]
Finished on https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/21
