### ISSUE TITLE
HU021 - Crear evento masivo.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#68]
Como organizador de eventos masivos registrado en SportApp, quiero crear eventos deportivos en SportApp para promover la participación y el interés en actividades deportivas.

[Detalle HU021](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU021)

La implementacion de esta historia de usuario incluye el cumplimiento de la [HA003](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/131): Escalabilidad en el registro de usuarios

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/16
