### ISSUE TITLE
HU022 - Consultar usuarios inscritos eventos.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#69]
Como organizador de un evento masivo quiero consultar los usuarios inscritos a un evento que he creado en SportApp para asegurarme que el evento se pueda realizar con éxito.

[Detalle HU022](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU022)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/35
