### ISSUE TITLE
HU023 - Consultar calendario de eventos.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#70]
Como organizador de un evento masivos quiero consultar el calendario de todos los eventos creados en SportApp para definir las fechas de mi evento y no se interponga con otros eventos del público objetivo.

[Detalle HU023](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU023)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/20
