### ISSUE TITLE
HU024 - Publicar eventos deportivos.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#71]
Como organizador de un evento masivos quiero publicar el evento creado para que los usuarios de SportApp puedan tener conocimiento e inscribirse al evento.

[Detalle HU024](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU024)

**Comment by sriveros21** [comment]
Closed in: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/16
