### ISSUE TITLE
HU025 - Asignar tarifas a eventos.

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#72]
Como organizador de un evento masivos quiero asignar una tarifa al evento creado en SportApp para que los usuarios puedan conocer su valor y pagarlo en el momento de la inscripción a este.

[Detalle HU025](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU025)

**Comment by sriveros21** [comment]
Done as part of the creation event implementation
