### ISSUE TITLE
HU026 - Sugerir rutas de usuario (Móvil).

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#73]
Como organizadores de eventos masivos que ofrecen servicios complementarios a los usuarios de SportApp quiero sugerir rutas de entrenamiento al usuario para que se complemente su actividad deportiva.

[Detalle HU026](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU026)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/43
