### ISSUE TITLE
HU39 - Notificar de modo múltiple en eventos masivos.(Móvil)

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#75]
Como deportista no profesional de la aplicación “SportApp” quiero que la aplicación me genere   notificaciones de eventos masivos para poder asistir a tiempo a los eventos.

[Detalle HU039](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU039)

El cumplimiento de esta HU incluye [HA009](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/137): Latencia en recomendaciones de eventos  y [HA016](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/144)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/40
