### ISSUE TITLE
HU038 - Notificar consumo de alimentos y bebidas. (Móvil)

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#76]
Como Deportista no profesional usuario con plan intermedio de “SportApp” quiero que la aplicación 
me genere notificaciones de consumo de alimentos y bebidas para mantener el perfil de consumo de cloría durante la sesión.

[Detalle HU038](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU038)

La finalizacion de esta historia incluye el cumplimiento de este criterio de arquitectura [HA007](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/135): Latencia en notificación de hidratación y Alimentación

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/43
