### ISSUE TITLE
HU031 - Integrar aplicación con Strava. (Móvil)

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#83]
Como deportista no profesional de la aplicación SportApp quiero poder integrarla con Strava para conectar mis entrenamientos e información con SportApp.

[Detalle HU031](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU031)

El cumplimiento de esta historia incluye la historia de arquitectura [HA011](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/139)  y [HA012](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/140)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/41
