### ISSUE TITLE
HU029 - Sugerir servicios de acompañamiento al deportista (Móvil).

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#85]
Como profesional de servicios complementarios quiero sugerir al usuario de SportApp servicios de acompañamiento para que el deportista tenga el servicio completo para su entrenamiento o asistencia a eventos.

[Detalle HU029](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU029)

El cumplimiento de esta historia incluye la [HA010](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/issues/138)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/43
