### ISSUE TITLE
HU027 - Sugerir eventos al usuario. (Móvil)

### ISSUE THREAD

**Issue by CristinaGM4** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#87]
Como Profesionales de servicios complementarios que ofrecen servicios a los usuarios de SportApp
quiero sugerir eventos de entrenamiento al usuario para que se complemente su actividad deportiva.

[Detalle HU027](https://github.com/lfnavarroj1/MISW4501-Proyecto-final-Grupo-9/wiki/HU027)

**Comment by sriveros21** [comment]
Finished on: https://github.com/rcelisc/MISW4501-Proyecto-final-Grupo-9/pull/40
