### ISSUE TITLE
Corregir escenario de calidad 17

### ISSUE THREAD

**Issue by lfnavarroj1** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#96]

**Comment by sriveros21** [comment]
Se realiza correcion del scenario e igualmente se logra identificar que puede ser abordado desde otra HA relacionada, queda documentado asi: 
ID Escenario | EC017
-- | --
Atributo de calidad | 17 – Escalabilidad.
Versión | 001
Fuente | Estímulo | Artefacto | Ambiente
Organizador del evento | Solicitud de registro de usuarios durante eventos masivos | Aplicación móvil | El sistema opera en condiciones normales, enfrentado picos de alta demanda
Respuesta | Medida de la respuesta
El sistema es capaz de gestionar las solicitudes de registro de hasta 1000 usuarios de manera simultánea, sin degradar el rendimiento. | Procesamiento de hasta 1000 registros simultáneos en el tiempo establecido, cada uno en menos de 3 segundos.
