### ISSUE TITLE
Corregir escenario de calidad 20

### ISSUE THREAD

**Issue by lfnavarroj1** [lfnavarroj1/MISW4501-Proyecto-final-Grupo-9#97]

**Comment by sriveros21** [comment]
Se realiza ajuste del escenario 20, quedando asi: 
ID Escenario | EC020
-- | --
Atributo de calidad | 20 - Escalabilidad
Versión | 001
Fuente | Estímulo | Artefacto | Ambiente
Deportista no profesional durante eventos masivos | Incremento significativo de solicitudes de comunicación con entrenadores o médicos | Aplicación móvil “SportApp” | El sistema opera en condiciones de alta demanda justo antes, durante y después de eventos masivos
Respuesta | Medida de la respuesta
El sistema escala automáticamente para garantizar la comunicación estable de los usuarios con entrenadores o médicos para antes, durante y después de eventos masivos | Capacidad del sistema para escalar y gestionar hasta 1000 conversaciones simultáneas entre usuarios, médicos y entrenadores, asegurando tiempos de respuesta rápidos y eficientes.
